server:
  port: 8089
spring:
  datasource:
  url: jdbc:mysql://localhost:3306/automobile
  username: root
  password: Ganglia#123
  driver-class-name: com.mysql.cj.jdbc.Driver
rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 5672
  queue: automobile
  exchange: demo-batch-exchange
  routing: automobile-route-key
springdoc:
  api-docs:
    enabled: true
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka
